dtb-$(CONFIG_ARCH_AXERA) += AX630C_emmc_arm64_k419.dtb AX630C_fastemmc_arm64_k419.dtb AX630C_nand_arm64_k419.dtb 
dtb-$(CONFIG_ARCH_AXERA) += m5stack-ax630c-cam.dtb
dtb-$(CONFIG_ARCH_AXERA) += m5stack-ax630c-lite-hdmi.dtb
dtb-$(CONFIG_ARCH_AXERA) += m5stack-ax630c-lite-unitv3.dtb
dtb-$(CONFIG_ARCH_AXERA) += m5stack-ax630c-lite.dtb
dtb-$(CONFIG_ARCH_AXERA) += m5stack-ax630c-module-llm.dtb
dtb-$(CONFIG_ARCH_AXERA) += nanokvm_pro_arm64_k419.dtb
