#ifndef __DTS_AX620E_RESERVE_MEM_DEFINE_H
#define __DTS_AX620E_RESERVE_MEM_DEFINE_H


#define ATF_RESERVED_START_HI 0x0
#define ATF_RESERVED_START_LO 0x40040000
#define ATF_RESERVED_SIZE_HI 0x0
#define ATF_RESERVED_SIZE_LO 0x40000

#define SUPPORT_ATF

#define OPTEE_BOOT
#ifdef OPTEE_BOOT
#define OPTEE_RESERVED_START_HI 0x0
#define OPTEE_RESERVED_START_LO 0x44200000
#define OPTEE_RESERVED_SIZE_HI 0x0
#define OPTEE_RESERVED_SIZE_LO 0x2000000
#endif

#ifdef SUPPORT_RISCV
#define RISCV_RESERVED_START_HI
#define RISCV_RESERVED_START_LO
#define RISCV_RESERVED_SIZE_HI
#define RISCV_RESERVED_SIZE_LO
#endif

#ifdef SUPPORT_RISCV_LOG_MEM
#define RISCV_LOG_MEM_RESERVED_START_HI
#define RISCV_LOG_MEM_RESERVED_START_LO
#define RISCV_LOG_MEM_RESERVED_SIZE_HI
#define RISCV_LOG_MEM_RESERVED_SIZE_LO
#endif

#ifdef SUPPORT_ISP_IMAGE
#define ISP_IMAGE_RESERVED_START_HI
#define ISP_IMAGE_RESERVED_START_LO
#define ISP_IMAGE_RESERVED_SIZE_HI
#define ISP_IMAGE_RESERVED_SIZE_LO
#endif

#ifdef SUPPORT_RAMDISK_HEADER
#define RAMDISK_HEADER_RESERVED_START_HI
#define RAMDISK_HEADER_RESERVED_START_LO
#define RAMDISK_HEADER_RESERVED_SIZE_HI
#define RAMDISK_HEADER_RESERVED_SIZE_LO
#endif

#ifdef SUPPORT_MODEL_DATA
#define MODEL_DATA_RESERVED_START_HI
#define MODEL_DATA_RESERVED_START_LO
#define MODEL_DATA_RESERVED_SIZE_HI
#define MODEL_DATA_RESERVED_SIZE_LO
#endif

#ifdef SUPPORT_RAMDISK
#define RAMDISK_START_ADDR
#define RAMDISK_SIZE
#endif

#ifdef SUPPORT_RECYCLE_CMM
#define CMM_RECYCLE_START_ADDR
#define CMM_RECYCLE_SIZE
#endif

#define BOOTARGS "mem=1024M console=ttyS0,115200n8 earlycon=uart8250,mmio32,0x4880000 board_id=0,boot_reason=0x0 initcall_debug=0 quiet loglevel=0 usbcore.autosuspend=-1 root=/dev/mmcblk0p16 rootfstype=ext4 rw rootwait blkdevparts=mmcblk0:768K(spl),512K(ddrinit),256K(atf),256K(atf_b),1536K(uboot),1536K(uboot_b),1M(env),6M(logo),6M(logo_b),1M(optee),1M(optee_b),1M(dtb),1M(dtb_b),256M(kernel),256M(kernel_b),29189M(ubuntu_rootfs)"
#define CMM_ARGS "anonymous,0,0x80000000,3072M"

#endif /* __DTS_AX620E_RESERVE_MEM_DEFINE_H */
