#ifndef _CVI_CUSTOM_MEMMAP_H_
#define _CVI_CUSTOM_MEMMAP_H_

#include "cvi_board_memmap.h"

#undef CVIMMAP_FRAMEBUFFER_ADDR
#undef CVIMMAP_FRAMEBUFFER_SIZE
#undef CVIMMAP_FREERTOS_ADDR
#undef CVIMMAP_FREERTOS_SIZE
#undef CVIMMAP_ION_SIZE
#undef CVIMMAP_KERNEL_MEMORY_ADDR
#undef CVIMMAP_KERNEL_MEMORY_SIZE

#define CVIMMAP_FRAMEBUFFER_ADDR 0x9ae80000  /* offset 430.5MiB */
#define CVIMMAP_FRAMEBUFFER_SIZE 0x580000  /* 5.5MiB */
#define CVIMMAP_FREERTOS_ADDR 0x9fe00000  /* offset 510.0MiB */
#define CVIMMAP_FREERTOS_SIZE 0x200000  /* 2.0MiB */
#define CVIMMAP_ION_SIZE 0x4a00000  /* 74.0MiB */
#define CVIMMAP_KERNEL_MEMORY_ADDR 0x80000000  /* offset 0.0KiB */
#define CVIMMAP_KERNEL_MEMORY_SIZE 0x1fe00000  /* 510.0MiB */

#endif /* _CVI_CUSTOM_MEMMAP_H_ */
